name: EssentiallyMisc
main: com.steamcraftmc.EssentiallyMisc.MainPlugin
version: '1.0'
author: rknapp
load: startup
commands:
  gamemode:
    aliases: [gm, creative, survival, adventure, spectator, gmc, gms, gma, gmp]
    description: Changes a player's gamemode.
    usage: /gamemode [c|s|a|p|creative|survival|adventure|spectator] [player]
    permission: essentials.gamemode
    permission-message: 'ยง4You do not have permission to use this command.'
    default: op
  fixlight:
    aliases: ['/fixlight']
    description: Fixes the chunk/block lighting in a given radius
    usage: /fixlight [radius]
    permission: essentials.fixlight
    permission-message: 'ยง4You do not have permission to use this command.'
    default: op
  fly:
    description: Allows for creative mode fly.
    usage: /fly [player]
    permission: essentials.fly
    permission-message: 'ยง4You do not have permission to use this command.'
    default: op
  heal:
    description: Heals a player.
    usage: /heal [player]
    permission: essentials.heal
    permission-message: 'ยง4You do not have permission to use this command.'
    default: op

